### ISSUE TITLE
Add a catalog number and define parent/child relationship

### ISSUE THREAD

**Issue by suhasHere** [wilaw/catalog-format#3]
We need the following
 - Add Catalog Seq Number and explain how it is related to Parent Seq Num
 - Make parent seq num independent of MoQT object number

**Comment by wilaw** [comment]
Proposal is to add two fields:

1.  Catalog sequence number (CSN)- a required  integer starting at 0 and monotonically increasing with each successive catalog update.
2.  Parent sequence number  (PSN) - an optional reference pointing at a prior (not necessarily previous) catalog sequence number. 

If the PSN is absent, then the catalog is an independent catalog. If it is present, then the catalog represents a delta update. Having a sequence number independent of the transport sequencing allows catalogs to be distributed over moq-transport, or http or another transport and still be interpreted correctly.
